---
title: "Moneyball - CUNY Data Science 621"
author: "Eric Hirsch"
date: "2/20/2021"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning =  FALSE, message = FALSE)
```

```{r}
library(Hmisc)
library(psych)
library(tidyverse)
library(skimr)
library(purrr)
library(tidyr)
library(tidyverse)
library(gridExtra)
library(lubridate)
library(fastDummies)
library(data.table)
library(mltools)
library(MASS)
library(car)
library(patchwork)
library(ggthemes)
```


```{r}

location <- "home"

if (location == "work"){
dfTrain <- read.csv("C:\\Users\\eric.hirsch\\Desktop\\Rstudio\\CUNY_621\\Baseball\\moneyball-training-data.csv", header=TRUE)
dfEval <- read.csv("C:\\Users\\eric.hirsch\\Desktop\\RStudio\\CUNY_621\\Baseball\\moneyball-evaluation-data.csv", header=TRUE)
} else
{
dfTrain <- read.csv("D:\\RStudio\\CUNY_621\\Baseball\\moneyball-training-data.csv", header=TRUE)
dfEval <- read.csv("D:\\RStudio\\CUNY_621\\Baseball\\moneyball-evaluation-data.csv", header=TRUE)
}

colnames(dfTrain)<-gsub("TEAM_","",colnames(dfTrain))
colnames(dfEval)<-gsub("TEAM_","",colnames(dfEval))

```

```{r}



EHWrangle_MissingValues_Imputation <- function(df, y)
{
  
#1. Missing Completely at Random (MCAR):
#2. Missing at Random (MAR):
#3. Missing Not at Random (MNAR)

dfImputedMean <- data.frame(
    sapply(df, function(x) ifelse(is.na(x), mean(x, na.rm = TRUE), x)))

dfImputedMedian <- data.frame(
    sapply(df, function(x) ifelse(is.na(x), median(x, na.rm = TRUE), x)))

dfOmit <- na.omit(df)

fla <- substitute(n ~ ., list(n = as.name(y)))
m1 <- lm(fla, dfImputedMean)
step1 <- stepAIC(m1, trace=FALSE)
s1 <- summary(step1)$adj.r.squared

fla2 <- substitute(n ~ ., list(n = as.name(y)))
m2 <- lm(fla2, dfImputedMedian)
step2 <- stepAIC(m2, trace=FALSE)
s2 <- summary(step2)$adj.r.squared

fla3 <- substitute(n ~ ., list(n = as.name(y)))
m3 <- lm(fla3, dfOmit)
step3 <- stepAIC(m3, trace=FALSE)
s3 <- summary(step3)$adj.r.squared

l1 <- vector(mode = "list", length = 5)
names(l1) <- c("df", "type", "r2mean", "r2median", "r2omit")

l1$r2mean = s1
l1$r2median = s2
l1$r2omit = s3

if (s1>=s2) {
  l1$type = "mean"
  l1$df=dfImputedMean
  
  print(c("type:", l1$type))
  print(c("r2mean:", round(l1$r2mean,4)))
  print(c("r2median:", round(l1$r2median,4)))
  print(c("r2omit", round(l1$r2omit,4)))
  
  return (l1$df)
}
else {
  l1$type = "median"
  l1$df=dfImputedMedian
  
  
  print(c("type:", l1$type))
  print(c("r2mean:", round(l1$r2mean,4)))
  print(c("r2median:", round(l1$r2median,4)))
  print(c("r2omit", round(l1$r2omit,4)))
  
  return (l1$df)
}
}
```


```{r message=FALSE, warning=FALSE}

EHExplore_Interactions_Scatterplots <- function(df, y, interaction) {

df <- select_if(df, is.numeric)
  
df[,interaction] <- as.factor(df[,interaction])
  
library(ggsci)
  
plot_list <- list()

for(i in 1:ncol(df)) {     
   
  p <- eval(substitute(ggplot(df, aes_string(df[ , i], y, color=interaction)) +
  geom_point() +
  geom_smooth(method = "lm") +
    xlab("") +
    theme(title = element_text(size=7), axis.title.x = element_text(size = 7), axis.title.y = element_text(size = 9), axis.text.x = element_text(size = 8), panel.grid.major.x = element_line(color="gray"), panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(), panel.grid.major.y=element_line(color="gray"), panel.background = element_rect(fill = "slategray1", color="darkslategray")) +
  scale_color_d3()+
  scale_fill_d3()+
  ggtitle(colnames(df)[i]), list(i=i)))
  plot_list[[i]] <- p 
  
}
  return(plot_list)
}


```

```{r}

EHExplore_Outliers_Boxplots <- function(df, size="small")
{

df <- select_if(df, is.numeric)
  
s <- 7
if (size=="large") {
  s <- 10
}
plot_list2 <- list()

for(i in 1:ncol(df)) {     
  
  qp <- toString(head(sort(round(df[,i],2)),5))
  qz <- toString(tail(sort(round(df[,i],2)),5))
  qk <- str_c("L:   ", qp, "\\\n", "H:   ", qz)
  
  p <- eval(substitute(ggplot(df, aes(df[,i])) +
          coord_flip() +  
          xlab(colnames(df)[i])  +
          ylab(qk) +
          theme(axis.title.x = element_text(size = s), axis.title.y = element_text(size = 9), axis.text.x = element_blank(), axis.ticks.x = element_blank(), panel.grid.major.x = element_blank(), panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(), panel.grid.major.y=element_line(color="gray"), panel.background = element_rect(fill = "slategray2", color="darkslategray")) +
          geom_boxplot(), list(i=i)))
  plot_list2[[i]] <- p 
  
  
}
return (plot_list2)
}


```

```{r}


EHExplore_Distributions_Histograms <- function(df, size = "small", hist_nbins = 20)
{
  
df <- select_if(df, is.numeric)
    
s <- 7
if (size=="large") {
  s <- 10
}

plot_list2 <- list()

for(i in 1:ncol(df)) {     
  
  qp <- toString(head(sort(round(df[,i],2)),5))
  qz <- toString(tail(sort(round(df[,i],2)),5))
  qk <- str_c("L:   ", qp, "\\\n", "H:   ", qz)
  
  p <- eval(substitute(ggplot(df, aes(df[,i])) +
          ylab(colnames(df)[i])  +
          xlab(qk) +
          theme(axis.title.x = element_text(size = s), axis.title.y = element_text(size = 9), axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.text.x = element_text(size=8),  panel.grid.major.x = element_blank(), panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(), panel.background = element_rect(fill = "slategray2", color="darkslategray"))  + 
  geom_histogram(bins=hist_nbins, fill="white", aes(y = stat(density))) +
      geom_density(col = "red"), list(i=i)))
  plot_list2[[i]] <- p 
  
}
return (plot_list2)
}

```



```{r}


EHExplore_Correlations_Scatterplots <- function(df, y, flip=FALSE)
{
  plot_list <- list()
  
  df <- select_if(df, is.numeric)
  
  for(i in 1:ncol(df)) {
  
    ct <- cor.test(df[,i], df[,y])
    
  xText <- str_c("Correlation: ", round(ct$estimate,2), "   p value: ", round(ct$p.value,2))
  
  x1 = df[[i]]
  y1 =y
  
  if(flip)
  {
    x1=y
    y1=df[[i]]
  }
  
    p <- ggplot(df, aes_string(x1, y1)) +
  geom_point(fill="navy", color="white") +
  geom_smooth(method = "loess", color="red", fill="lightcoral") +
  ylab(y) +
    xlab(xText) +
    theme(title = element_text(size=9), axis.title.x = element_text(size = 8), axis.title.y = element_text(size = 9), axis.text.x = element_text(size = 8), axis.ticks.x = element_blank(), panel.grid.major.x = element_blank(), panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(), panel.grid.major.y=element_line(color="gray"), panel.background = element_rect(fill = "slategray2", color="darkslategray")) +
  ggtitle(colnames(df)[i])

  p <- eval(substitute(p, list(i=i)))
  plot_list[[i]] <- p 
    
}
  return(plot_list)
}


```

```{r}

EHExplore_StandardPlots <-function(data, y, return_list = FALSE, h_nbins = 20)
{  
  
list1 <- EHExplore_Outliers_Boxplots(data)
list2 <- EHExplore_Distributions_Histograms(data, hist_nbins =  h_nbins)
list3 <- EHExplore_Correlations_Scatterplots(data, y)

zz2 <- list()

for(i in 1:length(list1)) {
zz2[i*3-2] <- list1[i]
zz2[i*3-1] <- list2[i]
zz2[i*3] <- list3[i]
}

lenZ <- length(zz2)
quotient <- lenZ %/% 9
gap <- lenZ - quotient*9
gaprows <- gap/3


for(i in 1:quotient) { 
  
  start <- (i-1)*9 + 1
  finish <- start + 8
   
  grid.arrange(grobs=zz2[c(start:finish)], ncol=3)
  
}

if (gaprows>0) {
  
  start <- quotient*9 + 1
  finish <- start + gaprows*3 - 1
   
  grid.arrange(grobs=zz2[c(start:finish)], ncol=3, nrow=gaprows)
}  


if (return_list) {
  return (zz2)
}

}

```
```{r}


EHExplore_Multicollinearity <-function(df, run_all=FALSE) {
  
dfCor <- as.data.frame(cor(df))
  
  if (run_all) {
pairs.panels(df)
print(dfCor)
  }
  

library(corrplot)
my_matrix <- df[]
cor_res <- cor(my_matrix, use = "na.or.complete")

z <- corrplot(cor_res, type = "upper", order = "original", tl.col = "black", tl.srt = 45, tl.cex = 0.55)
#return (z)

}
```



```{r}

EHModel_Regression_StandardLM <- function(df, y) {

fla <- substitute(n ~ ., list(n = as.name(y)))

par(mfcol=c(2,2))

mod_4 <- lm(fla, df)
step3 <- stepAIC(mod_4, trace=FALSE)
print(summary(step3))
print(plot(step3))

vif_values <- car::vif(step3)
print(vif_values)

return(step3)

}

```
```{r}

summary(dfTrain)
```



```{r}

EHExplore_StandardPlots(dfTrain, "TARGET_WINS")

```

```{r}
  EHExplore_Multicollinearity(dfTrain)
```
```{r}

EHModel_Regression_StandardLM(dfTrain, "TARGET_WINS")

```
```{r}

dfTrain1 <- dfTrain %>%
  dplyr::select(-BATTING_HBP, -BASERUN_CS)

dfTrain2 <- dfTrain1 %>%
  mutate(BSO_Missing_Flag = ifelse(is.na(BATTING_SO),1,0), BRSB_Missing_Flag = ifelse(is.na(BASERUN_SB),1,0), PSO_Missing_Flag = ifelse(is.na(PITCHING_SO),1,0), FDP_Missing_Flag = ifelse(is.na(FIELDING_DP),1,0))

dfEval1 <- dfTrain %>%
  dplyr::select(-BATTING_HBP, -BASERUN_CS)

dfEval2 <- dfEval1 %>%
  mutate(BSO_Missing_Flag = ifelse(is.na(BATTING_SO),1,0), BRSB_Missing_Flag = ifelse(is.na(BASERUN_SB),1,0), PSO_Missing_Flag = ifelse(is.na(PITCHING_SO),1,0), FDP_Missing_Flag = ifelse(is.na(FIELDING_DP),1,0))

a <- EHExplore_Interactions_Scatterplots(dfTrain2, "TARGET_WINS", "BSO_Missing_Flag")

grid.arrange(grobs=a[c(1:8)], ncol=2, nrow=4)
grid.arrange(grobs=a[c(9:16)], ncol=2, nrow=4)
grid.arrange(grobs=a[c(17:18)], ncol=2, nrow=1)

b <- EHExplore_Interactions_Scatterplots(dfTrain2, "TARGET_WINS", "BRSB_Missing_Flag")

grid.arrange(grobs=b[c(1:8)], ncol=2, nrow=4)
grid.arrange(grobs=b[c(9:16)], ncol=2, nrow=4)
grid.arrange(grobs=b[c(17:18)], ncol=2, nrow=1)

c <- EHExplore_Interactions_Scatterplots(dfTrain2, "TARGET_WINS", "PSO_Missing_Flag")

grid.arrange(grobs=c[c(1:8)], ncol=2, nrow=4)
grid.arrange(grobs=c[c(9:16)], ncol=2, nrow=4)
grid.arrange(grobs=c[c(17:18)], ncol=2, nrow=1)

d <- EHExplore_Interactions_Scatterplots(dfTrain2, "TARGET_WINS", "FDP_Missing_Flag")

grid.arrange(grobs=d[c(1:8)], ncol=2, nrow=4)
grid.arrange(grobs=d[c(9:16)], ncol=2, nrow=4)
grid.arrange(grobs=d[c(17:18)], ncol=2, nrow=1)

```
Transformations:

pitching_h

```{r}

dfPH <- dfTrain2 %>%
  dplyr::select(TARGET_WINS, PITCHING_H) %>%
  dplyr::filter(PITCHING_H <= 3000)

x <- EHExplore_Correlations_Scatterplots(dfPH, "TARGET_WINS")
print(x[[2]])

dfTrain2 <- dfTrain2 %>%
  mutate(Pitch_h_Under1500 = ifelse(PITCHING_H<=1500, 1, 0))

dfEval2 <- dfEval2 %>%
  mutate(Pitch_h_Under1500 = ifelse(PITCHING_H<=1500, 1, 0))


```

F_DP


```{r}


dfTrain2 <- dfTrain2 %>%
  mutate(Prod_DP_H = FIELDING_DP*PITCHING_H) %>%
  mutate(Inter_DP_H_Under1500 = FIELDING_DP*Pitch_h_Under1500)

dfEval2 <- dfEval2 %>%
  mutate(Prod_DP_H = FIELDING_DP*PITCHING_H) %>%
  mutate(Inter_DP_H_Under1500 = FIELDING_DP*Pitch_h_Under1500)
  
summary(lm(TARGET_WINS ~ FIELDING_DP, dfTrain2))$adj.r.squared
summary(lm(TARGET_WINS ~ FIELDING_DP + PITCHING_H + Prod_DP_H, dfTrain2))$adj.r.squared
summary(lm(TARGET_WINS ~ FIELDING_DP + Pitch_h_Under1500 + Inter_DP_H_Under1500, dfTrain2))$adj.r.squared

dfTrain2 <- dfTrain2 %>%
  dplyr::select(-Prod_DP_H)

dfEval2 <- dfEval2 %>%
  dplyr::select(-Prod_DP_H)
```

Home runs

```{r}

plot(dfTrain2$BATTING_HR, dfTrain$PITCHING_HR)

dfTrain2 <- dfTrain2 %>%
  dplyr::select(-PITCHING_HR)


dfEval2 <- dfEval2 %>%
  dplyr::select(-PITCHING_HR)

```

```{r}

dfTrain2 <- dfTrain2 %>%
  mutate(Bat_hr_Under60 = ifelse(BATTING_HR<=60, 1, 0))

dfEval2 <- dfEval2 %>%
  mutate(Bat_hr_Under60 = ifelse(BATTING_HR<=60, 1, 0))

summary(lm(TARGET_WINS ~ BATTING_HR, dfTrain2))$adj.r.squared
summary(lm(TARGET_WINS ~ BATTING_HR + Bat_hr_Under60, dfTrain2))$adj.r.squared

```
errors
```{r}

dfTrain2 <- dfTrain2 %>%
  mutate(E_sq = FIELDING_E^2)

dfEval2 <- dfEval2 %>%
  mutate(E_sq = FIELDING_E^2)

```


Missing "cohort"

```{r}

dfTrain2 <- dfTrain2 %>%
  mutate(Inter_bb_Cohort = PITCHING_BB*BSO_Missing_Flag) %>%
  mutate(Inter_E_Cohort = FIELDING_E*BSO_Missing_Flag) %>%
  mutate(Inter_bh_Cohort = BATTING_H*BSO_Missing_Flag) %>%
  mutate(Inter_bhr_Cohort = BATTING_HR*BSO_Missing_Flag) %>%
  mutate(Inter_bbb_Cohort = BATTING_BB*BSO_Missing_Flag) %>%
  mutate(Inter_bs_Cohort = BASERUN_SB*BSO_Missing_Flag) 

dfEval2 <- dfEval2 %>%
  mutate(Inter_bb_Cohort = PITCHING_BB*BSO_Missing_Flag) %>%
  mutate(Inter_E_Cohort = FIELDING_E*BSO_Missing_Flag) %>%
  mutate(Inter_bh_Cohort = BATTING_H*BSO_Missing_Flag) %>%
  mutate(Inter_bhr_Cohort = BATTING_HR*BSO_Missing_Flag) %>%
  mutate(Inter_bbb_Cohort = BATTING_BB*BSO_Missing_Flag) %>%
  mutate(Inter_bs_Cohort = BASERUN_SB*BSO_Missing_Flag) 
```


```{r}

dfTrain_Imputed<- EHWrangle_MissingValues_Imputation(dfTrain2, "TARGET_WINS")
step2 <- EHModel_Regression_StandardLM(dfTrain_Imputed, "TARGET_WINS")

```

categories
```{r}

dfTrain3 <- dfTrain2 %>%
  dplyr::filter(PSO_Missing_Flag==0) %>%
  dplyr::filter(PITCHING_H>1500)

dfCat <- dfTrain3 %>% mutate(category_PH=as.numeric(cut(PITCHING_H, breaks=c(-Inf, quantile(dfTrain3$PITCHING_H, 0.33), quantile(dfTrain3$PITCHING_H, 0.67), Inf), labels=c(1,2,3))))

dfCat <- dfCat %>% mutate(category_PBB=as.numeric(cut(PITCHING_BB, breaks=c(-Inf, quantile(dfTrain3$PITCHING_BB, 0.33), quantile(dfTrain3$PITCHING_BB, 0.67), Inf), labels=c(1,2,3))))

dfCat  <- dfCat %>% mutate(category_BH=as.numeric(cut(BATTING_H, breaks=c(-Inf, quantile(dfTrain3$BATTING_H, 0.33), quantile(dfTrain3$BATTING_H, 0.67), Inf), labels=c(1,2,3))))

dfCat  <- dfCat %>% mutate(category_BBB=as.numeric(cut(BATTING_BB, breaks=c(-Inf, quantile(dfTrain3$BATTING_BB, 0.33), quantile(dfTrain3$BATTING_BB, 0.67), Inf), labels=c(1,2,3))))

dfCat  <- dfCat %>% mutate(category_BHR=as.numeric(cut(BATTING_HR, breaks=c(-Inf, quantile(dfTrain3$BATTING_HR, 0.33), quantile(dfTrain3$BATTING_HR, 0.67), Inf), labels=c(1,2,3))))

dfCat <- dfCat %>%
  mutate(Hitting_Power = as.numeric(category_BH) + as.numeric(category_BBB)) %>%
  mutate(Pitching_Power = as.numeric(category_PH) + as.numeric(category_PBB))

summary(lm(TARGET_WINS ~ Hitting_Power + Pitching_Power, dfCat))
summary(lm(TARGET_WINS ~ category_PH + category_PBB + category_BH + category_BBB + category_BHR, dfCat))

ggplot(dfCat, aes(as.factor(Hitting_Power), TARGET_WINS)) +
         geom_boxplot()

ggplot(dfCat, aes(as.factor(Pitching_Power), TARGET_WINS)) +
         geom_boxplot()

```

Now we make predictions

```{r}

makePredictions <- function(m)
{
predictions <- as.data.frame(predict(m,newdata=dfEval2))
write_csv(predictions, "C:\\Users\\Eric\\Desktop\\predictionsBB.csv")
}

makePredictions(step2)

```
```

