---
title: "Untitled"
author: "Eric Hirsch"
date: "12/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Hmisc)
library(psych)
library(tidyverse)
library(skimr)
library(purrr)
library(tidyr)
library(tidyverse)
```


```{r}
dfTrain <- read.csv("D:\\RStudio\\621\\Baseball\\moneyball-training-data.csv", header=TRUE)
```

### Initial Exploration
```{r}
dim(dfTrain)
summary(dfTrain)
skim(dfTrain)
str(dfTrain)
```

### Outlier Analysis and zeroes as nas

```{r}


for(i in 2:ncol(dfTrain)) {                              
  print(ggplot(dfTrain, aes(dfTrain[ , i])) +
          coord_flip() +  
          xlab(colnames(dfTrain)[i])  +
          geom_boxplot())

  print(head(sort(dfTrain[,i])))
  
  print(tail(sort(dfTrain[,i])))

}


```

There are 4 categories where 0s may be nas:  Pitching and Batting HR and Pitching and batting SO.  We look more closely at these categories:

```{r}
dfTrain_ZeroAsNA <- dfTrain %>%
select(TEAM_PITCHING_SO, TEAM_PITCHING_HR, TEAM_BATTING_SO, TEAM_BATTING_HR)

hist(dfTrain_ZeroAsNA)

```

Will do nothing with outliers or na as zero for now

#### Taking care of NA


```{r}

dfTrain %>%
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram()

dfTrain %>%
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_boxplot() +
  coord_flip()

```


```{r}

hist(dfTrain$TARGET_WINS, bins=5)

head(sort(dfTrain$TARGET_WINS))

dfTrain_ZeroWins <- dfTrain %>%
  filter(TARGET_WINS ==0)

head(dfTrain_ZeroWins, 1)
```

```{r}

pairs.panels(dfTrain[1:8])
pairs.panels(dfTrain[9:17])

dfCor <- as.data.frame(cor(dfTrain))
dfCor
```
```{r}
cor.test(dfTrain$TEAM_PITCHING_HR, dfTrain$TARGET_WINS)

ggplot(dfTrain, aes(TEAM_PITCHING_HR, TEAM_BATTING_HR, color=INDEX)) +
  geom_point()
```

```{r}

hist(dfTrain$TEAM_PITCHING_HR, breaks=100)
plot(dfTrain$TEAM_PITCHING_HR, dfTrain$TARGET_WINS)

```
```{r}

m1 <- lm(TARGET_WINS ~ TEAM_PITCHING_HR, data=dfTrain)
summary(m1)
plot(m1)


library(car) 
influencePlot(m1, id.method='identify', main='Influence Plot', sub='Circle size is proportional to Cook’s distance')

```

```{r}

dfTrain2 <- dfTrain[-c(1211,2233,299,1825, 832), ]
cor.test(dfTrain2$TEAM_PITCHING_HR, dfTrain2$TARGET_WINS)

m2 <- lm(TARGET_WINS ~ TEAM_PITCHING_HR, data=dfTrain2)
summary(m2)
plot(m2)

library(car) 
influencePlot(m2, id.method='identify', main='Influence Plot', sub='Circle size is proportional to Cook’s distance')
```

```{r}


```
```{r}

summary(m1$residuals)
describe(m1$residuals)

dfTrain$Residuals <- m1$residuals
dfTrain$Fitted <- m1$fitted.values



```
```{r}

library(tidyverse)

```
```{r}

dfTrain_WithoutHR <- dfTrain %>%
  filter(TARGET_WINS >=50 | TEAM_PITCHING_HR!=0)

hist(dfTrain_WithoutHR$TEAM_PITCHING_HR)
plot(dfTrain_WithoutHR$TEAM_PITCHING_HR, dfTrain_WithoutHR$TARGET_WINS)
  
m3 <- lm(TARGET_WINS ~ TEAM_PITCHING_HR, data=dfTrain_WithoutHR)
summary(m3)
plot(m3)


library(car) 
influencePlot(m3, id.method='identify', main='Influence Plot', sub='Circle size is proportional to Cook’s distance')


```

```{r}
dfTrain_BiModal <- dfTrain %>%
  mutate(HR_Low = if_else(TEAM_PITCHING_HR<50,1,0)) %>%
  mutate(HR_High = if_else(TEAM_PITCHING_HR>=50,1,0))

dfCor_BiModal <- as.data.frame(cor(dfTrain_BiModal))

```

```{r}

m4 <- lm(TARGET_WINS ~ TEAM_PITCHING_HR + HR_Low, data=dfTrain_BiModal)
summary(m4)
plot(m4)

```
```{r}

dfHighHR <- dfTrain_BiModal %>%
  filter(HR_High ==1)

dfLowHR <- dfTrain_BiModal %>%
  filter(HR_Low==1)

t.test(dfLowHR$TARGET_WINS, dfHighHR$TARGET_WINS)

m5 <- lm(TARGET_WINS ~ TEAM_PITCHING_HR, data=dfHighHR)
summary(m5)
plot(m5)

```
```{r}
dfCor_HR <- as.data.frame(cor(dfTrain_BiModal[-1], dfTrain_BiModal$TEAM_PITCHING_HR)) 
dfCor_Low <- as.data.frame(cor(dfTrain_BiModal[-1], dfTrain_BiModal$HR_Low))

plot(dfTrain$TEAM_BATTING_HR, dfTrain$TEAM_PITCHING_HR)
```

```{r}

dfTrain$HR_Diff <- dfTrain$TEAM_PITCHING_HR -dfTrain$TEAM_BATTING_HR
hist(dfTrain$HR_Diff, breaks=100)

describe(dfTrain$HR_Diff)

```

Sum of HR allowed greatly exceeds sum of HR hit

```{r}



```

```{r}
m6 <- lm(dfTrain$TEAM_BATTING_HR ~ dfTrain$TEAM_PITCHING_HR)
summary(m6)
plot(m6)
```

```{r}


cor.test(dfTrain$TEAM_BATTING_BB, dfTrain$TEAM_PITCHING_BB)
plot(dfTrain$TEAM_BATTING_BB, dfTrain$TEAM_PITCHING_BB)

```

```{r}

hist(dfTrain$TARGET_WINS)
```

