---
title: "Moneyball - CUNY Data Science 621"
author: "Eric Hirsch"
date: "2/20/2021"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning =  FALSE, message = FALSE)
```

```{r}
library(Hmisc)
library(psych)
library(tidyverse)
library(skimr)
library(purrr)
library(tidyr)
library(tidyverse)
library(gridExtra)
library(lubridate)
library(fastDummies)
library(data.table)
library(mltools)
library(MASS)
library(car)
library(patchwork)
```

```{r message=FALSE, warning=FALSE}

EHExplore_Interactions_Scatterplots <- function(df, y, interaction) {

df <- select_if(df, is.numeric)
  
df[,interaction] <- as.factor(df[,interaction])
  
library(ggsci)
  
plot_list <- list()

for(i in 1:ncol(df)) {     
   
  p <- eval(substitute(ggplot(df, aes_string(df[ , i], y, color=interaction)) +
  geom_point() +
  geom_smooth(method = "lm") +
    xlab("") +
    theme(title = element_text(size=7), axis.title.x = element_text(size = 7), axis.title.y = element_text(size = 9), axis.text.x = element_text(size = 8), panel.grid.major.x = element_line(color="gray"), panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(), panel.grid.major.y=element_line(color="gray"), panel.background = element_rect(fill = "slategray1", color="darkslategray")) +
  scale_color_d3()+
  scale_fill_d3()+
  ggtitle(colnames(df)[i]), list(i=i)))
  plot_list[[i]] <- p 
  
}
  return(plot_list)
}


```

```{r}

EHExplore_Outliers_Boxplots <- function(df, size="small")
{

df <- select_if(df, is.numeric)
  
s <- 7
if (size=="large") {
  s <- 10
}
plot_list2 <- list()

for(i in 1:ncol(df)) {     
  
  qp <- toString(head(sort(round(df[,i],2)),5))
  qz <- toString(tail(sort(round(df[,i],2)),5))
  qk <- str_c("L:   ", qp, "\\\n", "H:   ", qz)
  
  p <- eval(substitute(ggplot(df, aes(df[,i])) +
          coord_flip() +  
          xlab(colnames(df)[i])  +
          ylab(qk) +
          theme(axis.title.x = element_text(size = s), axis.title.y = element_text(size = 9), axis.text.x = element_blank(), axis.ticks.x = element_blank(), panel.grid.major.x = element_blank(), panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(), panel.grid.major.y=element_line(color="gray"), panel.background = element_rect(fill = "slategray2", color="darkslategray"))  + 
          geom_boxplot(), list(i=i)))
  plot_list2[[i]] <- p 
  
  
}
return (plot_list2)
}


```

```{r}


EHExplore_Distributions_Histograms <- function(df, size = "small", hist_nbins = 100)
{
  
df <- select_if(df, is.numeric)
    
s <- 7
if (size=="large") {
  s <- 10
}

plot_list2 <- list()

for(i in 1:ncol(df)) {     
  
  qp <- toString(head(sort(round(df[,i],2)),5))
  qz <- toString(tail(sort(round(df[,i],2)),5))
  qk <- str_c("L:   ", qp, "\\\n", "H:   ", qz)
  
  p <- eval(substitute(ggplot(df, aes(df[,i])) +
          ylab(colnames(df)[i])  +
          xlab(qk) +
          theme(axis.title.x = element_text(size = s), axis.title.y = element_text(size = 9), axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.text.x = element_text(size=8),  panel.grid.major.x = element_blank(), panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(), panel.grid.major.y=element_blank(), panel.background = element_rect(fill = "slategray2", color="darkslategray"))  + 
  geom_histogram(bins=hist_nbins, fill="white", aes(y = stat(density))) +
      geom_density(col = "red"), list(i=i)))
  plot_list2[[i]] <- p 
  
}
return (plot_list2)
}

```



```{r}


EHExplore_Correlations_Scatterplots <- function(df, y, flip=FALSE)
{
  plot_list <- list()
  
  df <- select_if(df, is.numeric)
  
  for(i in 1:ncol(df)) {
  
    ct <- cor.test(df[,i], df[,y])
    
  xText <- str_c("Correlation: ", round(ct$estimate,2), "   p value: ", round(ct$p.value,2))
  
  x1 = df[[i]]
  y1 =y
  
  if(flip)
  {
    x1=y
    y1=df[[i]]
  }
  
    p <- ggplot(df, aes_string(x1, y1)) +
  geom_point(fill="navy", color="white") +
  geom_smooth(method = "loess", color="red", fill="lightcoral") +
  ylab(y) +
    xlab(xText) +
    theme(title = element_text(size=9), axis.title.x = element_text(size = 8), axis.title.y = element_text(size = 9), axis.text.x = element_text(size = 8), axis.ticks.x = element_blank(), panel.grid.major.x = element_blank(), panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(), panel.grid.major.y=element_line(color="gray"), panel.background = element_rect(fill = "slategray2", color="darkslategray")) +
  ggtitle(colnames(df)[i])

  p <- eval(substitute(p, list(i=i)))
  plot_list[[i]] <- p 
    
}
  return(plot_list)
}


```

```{r}

EHExplore_StandardPlots <-function(data, y, return_list = FALSE, h_nbins = 100)
{  
  
list1 <- EHExplore_Outliers_Boxplots(data)
list2 <- EHExplore_Distributions_Histograms(data, hist_nbins =  h_nbins)
list3 <- EHExplore_Correlations_Scatterplots(data, y)

zz2 <- list()

for(i in 1:length(list1)) {
zz2[i*3-2] <- list1[i]
zz2[i*3-1] <- list2[i]
zz2[i*3] <- list3[i]
}

lenZ <- length(zz2)
quotient <- lenZ %/% 9
gap <- lenZ - quotient*9
gaprows <- gap/3


for(i in 1:quotient) { 
  
  start <- (i-1)*9 + 1
  finish <- start + 8
   
  grid.arrange(grobs=zz2[c(start:finish)], ncol=3)
  
}

if (gaprows>0) {
  
  start <- quotient*9 + 1
  finish <- start + gaprows*3 - 1
   
  grid.arrange(grobs=zz2[c(start:finish)], ncol=3, nrow=gaprows)
}  


if (return_list) {
  return (zz2)
}

}

```

```{r}

EHAnalyze_Regression_StandardLM <- function(df, y) {

fla <- substitute(n ~ ., list(n = as.name(y)))

par(mfcol=c(2,2))

mod_4 <- lm(fla, df)
step3 <- stepAIC(mod_4, trace=FALSE)
print(summary(step3))
print(plot(step3))

vif_values <- car::vif(step3)
print(vif_values)

}

```

```{r}
data(gala, package="faraway")
dfGala <- gala %>%
  dplyr::select(-Endemics)

summary(dfGala)

```

```{r}



EHExplore_StandardPlots(dfGala,"Species")

```
```{r}

EHExplore_Multicollinearity <-function(df, run_all=FALSE) {
  
dfCor <- as.data.frame(cor(df))
  
  if (run_all) {
pairs.panels(df)
print(dfCor)
  }
  

library(corrplot)
my_matrix <- df[]
cor_res <- cor(my_matrix, use = "na.or.complete")

z <- corrplot(cor_res, type = "upper", order = "original", tl.col = "black", tl.srt = 45, tl.cex = 0.55)
#return (z)

}
```


```{r}
data(hsb, package="faraway")
dfHsb <- hsb

summary(dfHsb)

```
```{r}

dfHsb_Numeric <- as.data.frame(one_hot(as.data.table(dfHsb), dropCols=TRUE))

EHExplore_StandardPlots(dfHsb_Numeric, "math")

```

```{r}

EHAnalyze_Regression_StandardLM(dfHsb, "math")

```
```{r}

EHExplore_Multicollinearity(dfHsb_Numeric, run_all = TRUE)
```
```{r}
data(dvisits, package="faraway")

summary(dvisits)

```

```{r}

dvisits <- dvisits %>%
  dplyr::select(-agesq)
```

```{r}

EHExplore_StandardPlots(dvisits, "doctorco")
```

```{r}

EHExplore_Multicollinearity(dvisits)

EHAnalyze_Regression_StandardLM(dvisits, "doctorco")


```

```{r}

data(sat, package="faraway")

summary(sat)

```

```{r}

EHExplore_StandardPlots(sat, "total", h_nbins = 10)

```
```{r}

EHExplore_Multicollinearity(sat, run_all = TRUE)

```
```{r}

sat2 <- sat %>%
  dplyr::select(expend, takers, total) %>%
  mutate(taksq = takers^2, expnd_cat = ifelse(expend>5.78, 1, 0), extainter = expnd_cat*takers)

EHAnalyze_Regression_StandardLM(sat2, "total")

```

```{r}

sat3 <- sat %>%
  mutate(expnd_cat = ifelse(expend>5.78, 1, 0))

wrap_plots(EHExplore_Interactions_Scatterplots(sat3, "total", interaction = "expnd_cat"))

```

```{r}

data(punting, package="faraway")

summary(punting)

```
```{r}

EHExplore_StandardPlots(punting, "Distance", h_nbins = 10)

```
```{r}

EHExplore_Multicollinearity(punting, run_all =  TRUE)

```
```{r}

EHAnalyze_Regression_StandardLM(punting, "Distance")
summary(lm(Distance ~ Hang, punting))
summary(lm(Distance ~ OStr + Hang, punting))

```

```{r}


punting2 <- punting %>%
  mutate(RFooted = ifelse(RStr>=LStr, 1, 0))

summary(punting2$RFooted)
```

```{r}

wrap_plots(EHExplore_Interactions_Scatterplots(punting2, "Distance", "RFooted"))

punting3 <- punting2 %>%
  mutate(LsInter = LStr*RFooted, Rsinter = RStr*RFooted, Rfinter = RFlex*RFooted, rhang = Hang*RFooted)

punting4 <- punting3 %>%
  dplyr::select(-Hang, -OStr)

EHAnalyze_Regression_StandardLM(punting4, "Distance")

```



