---
title: "Untitled"
author: "Eric Hirsch"
date: "3/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
devtools::install_github("ericonsi/EHData")
library(EHData)
library(patchwork)
library(gridExtra)
library(ggsci)
```
```{r}

df <- read.csv("D:\\RStudio\\CUNY_621\\Assignment 3\\crime-training-data_modified.csv")
```

```{r}

summary(df)
str(df)

```
```{r}
library(psych)

EHSummarize_StandardPlots(df, "target", type="box")
EHExplore_Multicollinearity(df, run_all=TRUE)

```

```{r}

dfM <- df %>%
  mutate(znM = zn*-1, rmM = rm*-1 )
```

 
```{r}

EHModel_Regression_Logistic(df, "target")
```
```{r}

df2 <- df %>%
  mutate_at(c(1:12), scale)

EHModel_Regression_Logistic(df2, "target")

```

```{r}

df1 <- df %>%
  dplyr::select(nox, dis, rad, ptratio, medv, target)

EHModel_Regression_Logistic(df1, "target")


```
```{r}

dfT <- df %>%
  mutate(TaxOver600 = ifelse(tax>=600,1,0))

EHExplore_Interactions_Scatterplots(dfT, "target", "TaxOver600")

```

```{r}

dfT2 <- df %>%
  mutate(IndusOver16 = ifelse(indus>=16,1,0))

EHExplore_Interactions_Scatterplots(dfT2, "target", "IndusOver16")

```

```{r}

df4 <- dfT %>%
  mutate(lstatOver12 = ifelse(lstat>12,1,0), Inter_taxOver600_lstat = TaxOver600*lstat, Inter_lstatOver12_medv = lstatOver12*medv, IndusOver16 = ifelse(indus>=16,1,0)) 

EHExplore_TwoCategoricalColumns_Barcharts(dfT, "TaxOver600")
EHExplore_Interactions_Scatterplots(df4, "target", "lstatOver12")
```

```{r}


plot(EHModel_Regression_Logistic(df4, "target")) 

```

```{r}


df5 <- df4 %>%
  dplyr::filter(rownames(df4) != "338")

df6 <- df5 %>%
  dplyr::select(-IndusOver16) %>%
  mutate(zn=log(zn+1))


plot(EHModel_Regression_Logistic(df5, "target"))


```

