---
title: "What’s So Great about Heteroskedasticity?"
author: "Eric Hirsch, CUNY 621"
date: "2/27/2022"
output: html_document
---

```{r setup, include=FALSE, warnings=FALSE, messages=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings=FALSE, messages=FALSE)

#devtools::install_github("ericonsi/EHData", force=TRUE)

library(lmtest)
library(dplyr)
library(MASS)
library(EHData)
library(gridExtra)
library(tidyverse)


```


```{r}
list

library(tidyverse)
#dfx <- read.csv("D:\\RStudio\\CUNY_621\\AdRevenue.csv", head=TRUE)
dfx <- read.csv("C:\\Users\\eric.hirsch\\Desktop\\RStudio\\CUNY_621\\AdRevenue.csv", head=TRUE)

dfx <- dfx %>% 
  dplyr::select(AdRevenue, Circulation) %>%
  filter(Circulation <= 6) %>%
  filter(!row_number() == 3)

summary(dfx)


```



```{r, warnings=FALSE, messages=FALSE}
library(lmtest)
dfx1 <- dfx %>%
  dplyr::select(AdRevenue, Circulation)

p <- lm( AdRevenue ~ Circulation, dfx1)
summary(p)
plot(p, which = c(3))

bptest(p)
dwtest(p)  #No correlation is between 1 and 3
```



```{r warnings=FALSE, messages=FALSE}

q <- lm(log(AdRevenue) ~ Circulation, dfx)

plot(q, which = c(3))

bptest(q)
```

```{r}

wt <- 1 / lm(abs(p$residuals) ~ p$fitted.values)$fitted.values^2

#perform weighted least squares regression
r <- lm(AdRevenue ~ Circulation, data = dfx, weights=wt)

#view summary of model
summary(r)
plot(r, which=c(3))

bptest(r)
```

